### ISSUE TITLE
Component not Working on opportunity entity

### ISSUE THREAD

**Issue by MikeKob365** [GorgonUK/Modern-Dropzone-PCF#12]
The component works fine for all entities except the opportunity,
below is the error upon uploading a file:

![issue](https://github.com/user-attachments/assets/33408d09-cb7e-4663-ac42-c44af6d7c03c)

Appreciate your support on this matter.

**Comment by GorgonUK** [comment]
The component only works with entities that have notes enabled.

**Comment by MikeKob365** [comment]
I double checked it and the opportunity entity already has the notes enabled, I even tried it on a different environment and got the same error.
it worked on Quotes, Accounts and all other custom entities. the only one with issues is the opportunity.

**Comment by GorgonUK** [comment]
Fixed in Release 1.7
