### ISSUE TITLE
SharePoint View do not work for records without notes

### ISSUE THREAD

**Issue by jueludwig** [GorgonUK/Modern-Dropzone-PCF#13]
If a record has no notes and you switch to the SharePoint view, the view remains empty.
If you add a note, the view works.

**Comment by GorgonUK** [comment]
It should work just fine without having existing notes. Make sure to download the latest version of the PCF control and clearing the browser's cache.

**Comment by jueludwig** [comment]
i'm using the latest verison:
![image](https://github.com/user-attachments/assets/51963e20-76d7-4ae5-b4cf-700787001b29)
1.0.10

Bowsers cache is clean:

![chrome_VT4mF1FssU](https://github.com/user-attachments/assets/ceb93345-3e66-4802-a4ce-aeb868c7ecb6)

**Comment by GorgonUK** [comment]
I was able to replicate the issue you had and working on a patch.

**Comment by GorgonUK** [comment]
Fixed in release 1.7
