### ISSUE TITLE
GUID caching is too aggressive 

### ISSUE THREAD

**Issue by emibanana** [GorgonUK/Modern-Dropzone-PCF#17]
Hi, there some issue with the latest version:

when i just created a new record (entity with note attachment enabled), and i save the record:

1. the dropzone pcf would initially store a guid that doesnt exist, in the cache (I assume and feel like its the case)
2. then i save the record, which dataverse will then assign a new guid from their backend database
3. dropzone cached guid is then not inline with the actual one, see attached screenshot
![image](https://github.com/user-attachments/assets/a18c6f20-6d7e-4552-bc27-14344c71a653)

This also happen when i switch entity record using the quick switching panel, cached guid from dropzone is not updated, causing you viewing previous entity attachment.

This is further confirmed by doing a hard refresh ctrl + F5, it will be fixed.

**Comment by GorgonUK** [comment]
Hi @emibanana, 
Thank you for raising this. I will look into this.

**Comment by emibanana** [comment]
> Hi @emibanana, Thank you for raising this. I will look into this.

Thanks! you are the best!!!!

also just additional note and sorry for messaging on saturday...

I just imported an older "worked before" version of your solution, and did a complete "replace" of the solution, but its still have the same issue, could this because microsoft has changed something on their end for blob storage caching?

but my canvas app preview still works, my canvas app does direct query to the database for note attachment base64 every time a new record is loaded, so it doesnt seem to have issue

**Comment by emibanana** [comment]
Hi, confirmed its all fixed for me, for note attachment upload / preview file list.

Thank you for your speedy hot fix!

**Comment by GorgonUK** [comment]
Great to hear that. If you experience any other issue, do let me know.
