### ISSUE TITLE
TypeError when any related Notes do not have file attachments

### ISSUE THREAD

**Issue by hucklebridge** [GorgonUK/Modern-Dropzone-PCF#19]
When using the Dropzone control against a record and one or more Notes related to that record do not have files attached, the control appears to abort rendering. When this occurs, the following error message is logged to the browser console:

![image](https://github.com/user-attachments/assets/aac27a68-a128-46fb-8966-24502dce2470)

If **all** Notes related to a given record have files attached, the control otherwise works as expected.

**Comment by AleehaMaher** [comment]
<img width="935" alt="Screenshot 2024-08-19 175928" src="https://github.com/user-attachments/assets/d641aad6-469c-4d44-bf42-43753591ea77">

how you fix that error

**Comment by GorgonUK** [comment]
Could you double check your webpackConfig.js

node_modules/pcf-scripts/webpackConfig.js

![image](https://github.com/user-attachments/assets/37422b5b-5a44-4c2e-a5f9-bcce8255a3bc)

**Comment by GorgonUK** [comment]
> When using the Dropzone control against a record and one or more Notes related to that record do not have files attached, the control appears to abort rendering. When this occurs, the following error message is logged to the browser console:
> 
> ![image](https://private-user-images.githubusercontent.com/52218772/359101803-aac27a68-a128-46fb-8966-24502dce2470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTMyNzQsIm5iZiI6MTcyNDA5Mjk3NCwicGF0aCI6Ii81MjIxODc3Mi8zNTkxMDE4MDMtYWFjMjdhNjgtYTEyOC00NmZiLTg5NjYtMjQ1MDJkY2UyNDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE4NDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4Zjc3ZjZjMDYzODQxM2UxNmZkYWIxYjc5YTY0ZjhiNjBjMWUxODIwMzNkMWY4OWIxM2Q5ZjJhMzBiNmJhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ng7wauC19-hymxBtzLizeMHpra6ZFDE_EzWJZ7QePWE)
> 
> If **all** Notes related to a given record have files attached, the control otherwise works as expected.

I will look into that.

**Comment by GorgonUK** [comment]
> When using the Dropzone control against a record and one or more Notes related to that record do not have files attached, the control appears to abort rendering. When this occurs, the following error message is logged to the browser console:
> 
> ![image](https://private-user-images.githubusercontent.com/52218772/359101803-aac27a68-a128-46fb-8966-24502dce2470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDE4MjcsIm5iZiI6MTcyNTEwMTUyNywicGF0aCI6Ii81MjIxODc3Mi8zNTkxMDE4MDMtYWFjMjdhNjgtYTEyOC00NmZiLTg5NjYtMjQ1MDJkY2UyNDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEwNTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNjljMDIxMDU0MWFiZjZhYWM5YTczNDBhNzQ3ZTM3MDhjOWFkMjg4ZGFhYTcyYWI5NGFlMTc3NWE2ZDEwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4aQwE23VC2EjbAbn2pMxh-HU65esoHs_oqtHZmIGv88)
> 
> If **all** Notes related to a given record have files attached, the control otherwise works as expected.

This is very strange, I wasn't able to replicate this. 

Could you provide a short video to play back the steps you did to get this error?

**Comment by hucklebridge** [comment]
> > When using the Dropzone control against a record and one or more Notes related to that record do not have files attached, the control appears to abort rendering. When this occurs, the following error message is logged to the browser console:
> > ![image](https://private-user-images.githubusercontent.com/52218772/359101803-aac27a68-a128-46fb-8966-24502dce2470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDE4MjcsIm5iZiI6MTcyNTEwMTUyNywicGF0aCI6Ii81MjIxODc3Mi8zNTkxMDE4MDMtYWFjMjdhNjgtYTEyOC00NmZiLTg5NjYtMjQ1MDJkY2UyNDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEwNTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNjljMDIxMDU0MWFiZjZhYWM5YTczNDBhNzQ3ZTM3MDhjOWFkMjg4ZGFhYTcyYWI5NGFlMTc3NWE2ZDEwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4aQwE23VC2EjbAbn2pMxh-HU65esoHs_oqtHZmIGv88)
> > If **all** Notes related to a given record have files attached, the control otherwise works as expected.
> 
> This is very strange, I wasn't able to replicate this.
> 
> Could you provide a short video to play back the steps you did to get this error?

@GorgonUK I have provided the replication steps below, but do let me know if you're unable to get the same issue following them and I'll happily follow up with screenshots/a recording. However, I do also have a suspicion of what the problem is.

### To replicate:
1. Against an eligible Table, add both the Dropzone and the standard Timeline controls to a form.
2. Upload a document to a record via the Dropzone component and Refresh, confirming the document appears both in the Dropzone control and in Note form in the Timeline control.
3. Against the Timeline control, add a new note manually, providing any content for the Title and any content for the text/note body. Do not upload a file attachment to the note record. Save the new note record.
4. Refresh the record again. The Dropzone control will fail to render, citing the error message mentioned in the original comment, but will display fine in the Timeline control.

This occurs on both version 2.1 and the latest version (2.3) of the Dropzone control, and on both the latest versions of Chrome and Edge.


### Possible cause
Based on the error message, my theory is that this may be the result of needing to modify the filter statement used when retrieving related notes. The __getRelatedNotes__ function (line 37 of DataverseActions.tsx) has the following filter statement:

The error message itself is invoked by the [getFilteredAndSortedFiles](https://github.com/GorgonUK/Modern-Dropzone-PCF/blob/a0ee0bc949f97e78d6afa0099a4919aff939f82f/Dropzone/Landing/Landing.tsx#L1257) function of the Landing.tsx component, which explicitly tries to check the filename property against a search string. The error is caused when a filename value is null and is then accessed by __toLowerCase__.

The source of the notes/files is the [getRelatedNotes](https://github.com/GorgonUK/Modern-Dropzone-PCF/blob/a0ee0bc949f97e78d6afa0099a4919aff939f82f/Dropzone/DataverseActions.tsx#L37) function within DataverseActions.tsx, which includes a filter statement:

``const filter = `_objectid_value eq ${metadata.entityId}`;``

This correctly filters annotations to records related to the current record, but at no step in the process does there appear to be explicit checks/filtering to ensure that every related annotation has a file attachment, which in turn would then cause problems when properties like filename, which would only ever have value in the event of a file being attached, are accessed. If this is the root cause, extending the filter to include the `isdocument` property may resolve the issue, as follows:

``const filter = `_objectid_value eq ${metadata.entityId} and isdocument eq 1`;``

Hope this helps - let me know if there's any more information I can provide.

**Comment by GorgonUK** [comment]
You're absolutely correct. This scenario is something I had previously overlooked unfortunately. I will have a look at ways to resolve this.

**Comment by GorgonUK** [comment]
Fixed in release 2.4
