### ISSUE TITLE
[Feature Request] Option to show/hide the SharePoint Documents toggle

### ISSUE THREAD

**Issue by hucklebridge** [GorgonUK/Modern-Dropzone-PCF#20]
Currently, the Dropzone control shows the "SharePoint Documents" toggle option both when the table does and does not have SharePoint integration configured (but places the toggle into a disabled state in the latter scenario).

![image](https://github.com/user-attachments/assets/036fe37b-c021-42d9-849e-bd932fcc3103)

I believe the addition of a dedicated property to the control to allow the hiding of this toggle would prove extremely beneficial. The two main scenarios I can see for this being helpful are:

- The Dropzone control is being used against a table that is not configured to use SharePoint integration (and therefore the toggle is redundant)
- The table in question is configured to use SharePoint integration, but it is preferred that the control write to/read from Notes instead.

**Comment by GorgonUK** [comment]
Thanks for raising this. I will look into it.

**Comment by GorgonUK** [comment]
@hucklebridge, your request is Included in[ release 2.3](https://github.com/GorgonUK/Modern-Dropzone-PCF/releases/tag/2.3Release)

**Comment by hucklebridge** [comment]
@GorgonUK Thanks for this, much appreciated!
