### ISSUE TITLE
Control doesnt appear

### ISSUE THREAD

**Issue by bernierainerguy** [GorgonUK/Modern-Dropzone-PCF#21]
Hi, the control doesnt always appear - it does occasionally but mostly it does not. Anything i can look at?  Ive tried older versions but no luck there.

**Comment by bernierainerguy** [comment]
further to my last.  It looks like if the record is pre-existing and with a sharepoint connection record already - it doesnt display the control.  If its a new record, the control is displayed but the sharepoint switch is greyed until you go to documents,to get the connection record created then its no longer greyed.  In summary - it works if a new record, its just the retro fit to existing records it seems to have a problem with ie. with an existing sharepoint location.

**Comment by GrassoIsmaele** [comment]
Hi @bernierainerguy it's the same for me, it has troubles with extisitng records, searching for some property.

![Immagine 2024-09-23 145120](https://github.com/user-attachments/assets/0621d345-7022-4f70-8322-6517fe17de0a)

here: 

`            getFilteredAndSortedFiles() {
                var {files: e, notesSearchText: t} = this.state;
                return e.filter((e => e.filename.toLowerCase().includes(t.toLowerCase())))
            }`
Seems like that at some point e it's an empty array.
![image](https://github.com/user-attachments/assets/027d5fec-cc9b-478b-aa05-86da93042369)

@GorgonUK do you have any idea or suggestion? You've done a very great job on the connector but for my case, it would be on existing enviroments.

Have a nice day!

**Comment by bernierainerguy** [comment]
I agree, its a great connector and would be nice if it worked with existing records, also like the idea of defaulting to SharePoint.  Im sure no one would want the storage to be in the database.

**Comment by GrassoIsmaele** [comment]
Yeah, that probably should be a settings in the configuration process, user tends to make "messy operations".
Also because of the nature of dynamics, the link with Sharepoint it's made only when the user lands in the Sharepoint grid, so to upload files it requires a refresh of the page and my users are not very happy to do that, probably it's not possible to avoid that behavior, but I think that you could easily (more ore less) replicate it beacuse it's guid_name

**Comment by GorgonUK** [comment]
> further to my last. It looks like if the record is pre-existing and with a sharepoint connection record already - it doesnt display the control. If its a new record, the control is displayed but the sharepoint switch is greyed until you go to documents,to get the connection record created then its no longer greyed. In summary - it works if a new record, its just the retro fit to existing records it seems to have a problem with ie. with an existing sharepoint location.

@bernierainerguy What you're mentioning here is something I've been aiming to fix for awhile. In essence, what happens is that when you create a new record with Sharepoint documents enabled, the ID of the document location is set to 0000-0000-000000. If you then create create another document location for the same record, both document locations get a sensible ID. 

@GrassoIsmaele This is odd. I will add some conditions around the toLowerCase() function. I will look into your suggestion also.

I'm happy to implement a refresh button if there is enough demand for it.
