### ISSUE TITLE
Option to hide the "Enable SharePoint Documents" toggle for the end-users

### ISSUE THREAD

**Issue by thatapiguy** [GorgonUK/Modern-Dropzone-PCF#22]
It would be nice to just keep SharePoint Document as the default and not have the end-users having to enable it before uploading. 
Use Case: User uploaded documents should always go to the integrated SharePoint site , otherwise the user has to decide where to upload (which generally an end-user wouldn't care about.

**Comment by GorgonUK** [comment]
Fixed in release 2.4
