### ISSUE TITLE
Vulnerabilities on: x-data-spreadsheet 

### ISSUE THREAD

**Issue by GrassoIsmaele** [GorgonUK/Modern-Dropzone-PCF#23]
Hi, I've noticed that your project it's using **"x-data-spreadsheet": "^1.1.9"**, which is vulnerable because it relies on node-fetch  <2.6.7.

Do you have in plan some updates or maybe a change of library?

**Comment by GorgonUK** [comment]
I will look into this in the coming days.

**Comment by GorgonUK** [comment]
Fixed in 2.5 hotfix
