### ISSUE TITLE
Option to hide buttons

### ISSUE THREAD

**Issue by judema70** [GorgonUK/Modern-Dropzone-PCF#25]
Hi,

Very nice component!
However: 
-If I select a Word document, the Preview button is grayed-out.
-If I select an Excel, Preview button is enable, but preview is empty.
-What's the use of the duplicate button?

I'd like to see that we can control the visibility of all the buttons (similar as the SP button)

**Comment by GorgonUK** [comment]
Hi Judema70

1) Word is grayed out because we can't effectively parse it in the front-end.
2) I removed the dependency that allowed excel docs to be previous - will fix that.
3) Duplicate does what it says on the tin. It can be removed if it serves no purpose.
