### ISSUE TITLE
2.6 - Cannot import - Publisher name changed

### ISSUE THREAD

**Issue by dataverseDev** [GorgonUK/Modern-Dropzone-PCF#29]
Really appreciate your work on the component, but it is not possible to import the latest version if had a previous version deployed.

You mention this in your note against 2.6, but changing the publisher causes issues for solutions that depend on your component. It's a lot of work to remove the dependencies on the older versions, to be able to remove it and then import the new version, and then re-add to the forms.

Please can you confirm this change in publisher names won't happen again?

Thank you

**Comment by GorgonUK** [comment]
I can confirm it won't happen again. It's a one-off thing.
