### ISSUE TITLE
[feature request] PDF file preview

### ISSUE THREAD

**Issue by emibanana** [GorgonUK/Modern-Dropzone-PCF#6]
Hi this is an awsome PCF control! thanks for your hard work!

Just wondering if i can request a feature that just like the OOB note attachment control, to allow for a pop up preview of the file content utilising the browswer's pdf preview feature?

Potentially image preview as well but PDF is just about what i only wish it to have, so i can completely replace any drop file upload control and any time line control in my app.

![image](https://github.com/GorgonUK/Modern-Dropzone-PCF/assets/120373920/8865caa1-ccfa-4ce8-adfe-a141600b6b30)

**Comment by emibanana** [comment]
> Thank you for this great idea. I will include this in the next version of this PCF.

Appreciated! You are a very coooooooooooool developer!

**Comment by GorgonUK** [comment]
Your request has been included in the 1.5 release:

[1.5 Release](https://github.com/GorgonUK/Modern-Dropzone-PCF/releases/tag/1.5Release)

**Comment by emibanana** [comment]
The preview feature works like a charm! Thank you!

Just one small thing I think it's good to have:

double click to toggle preview, is that possible?

Currently double clicking doesnt do anything so I think its a feature good to have!

**Comment by GorgonUK** [comment]
I will consider it, but it's not really necessary.
