### ISSUE TITLE
Add Configuration Options for SharePoint in PCF

### ISSUE THREAD

**Issue by PowerThomas** [GorgonUK/Modern-Dropzone-PCF#9]
### Overview
I would like to request the addition of configuration options in the PCF control for attachments to enhance its usability and flexibility. The requested features include:

1. **Enable/Disable SharePoint Option**: Allow the Maker to decide whether the option to use SharePoint as the storage location is available to end users.
2. **Predefine SharePoint Location**: When SharePoint is enabled, provide a configuration setting to predefine the SharePoint location. This removes the need for end users to select a SharePoint location, thereby streamlining the process and reducing potential errors.

### Benefits

1. **Improved Control**: Makers will have more control over how attachments are managed, ensuring consistency across the application.
2. **Enhanced User Experience**: End users will experience a more straightforward and error-free process when dealing with attachments, as the SharePoint location can be predefined.
3. **Reduced Configuration Overhead**: By allowing Makers to predefine settings, the configuration process becomes more efficient and less prone to mistakes.

### Implementation Suggestions

1. Add a toggle option in the PCF control configuration to enable or disable the SharePoint option.
2. Include a field in the configuration settings where the SharePoint location can be specified by the Maker when the SharePoint option is enabled.

**Comment by GorgonUK** [comment]
Thank you for your suggestions, Thomas. 

Both are excellent ideas. I will work through this to fit your request in the next release.

**Comment by WilbertWalrus** [comment]
> 2\. **Predefine SharePoint Location**: When SharePoint is enabled, provide a configuration setting to predefine the SharePoint location. This removes the need for end users to select a SharePoint location, thereby streamlining the process and reducing potential errors.

If I may I add to this. User (such as an Admin) may belong to multiple departments and would need a list of SharePoint sites available to choose from. Maybe a checkbox with "Remember My Choice" so it stays on that selection for next time. 

@GorgonUK — do you have a timeline for the next release? If not, we will do this internally and force SharePoint (no need for a toggle) as Dataverse storage is expensive

**Comment by GorgonUK** [comment]
@WilbertWalrus Enabling cross SP site functionality requires major rework in the PCF. You can select it individually for now. There is a possibility I might incorporate a "Save my choice" functionality in the future if there is enough demand for it.

![CleanShot 2024-07-08 at 4  11 12@2x](https://github.com/GorgonUK/Modern-Dropzone-PCF/assets/59618079/bb1747d7-2604-4101-8af8-6480d0ceea6f)

**Comment by GorgonUK** [comment]
User's preference is now saved to local storage.
